[DMS-71] Selectively allow natural key updates
Ed-Fi-Alliance-OSS/Data-Management-Service pull request #245
Opened 2024-08-26 14:40 UTC by simpat-adam

2024-08-26 18:13 UTC, stephenfuqua commented on src/tests/EdFi.DataManagementService.Tests.E2E/Features/Resources/UpdateResourcesValidation.feature
> +        Scenario: 18 Verify clients can update the identity of resources that allow identity updates
👍

2024-08-26 18:25 UTC, bradbanister requested changes
`AllowIdentityUpdateOverrides` is not a database-level override. It should be overriding the `ResourceInfo.AllowIdentityUpdates` boolean field that is part of, for example, `IUpdateRequest`. Suggest doing this in `BuildResourceInfoMiddleware`.

2024-08-26 18:28 UTC, bradbanister commented on src/backend/EdFi.DataManagementService.Backend.Postgresql/Operation/UpdateDocumentById.cs
> +                        "Updating Natural Key - {TraceId}",
Use "Updating identity" not "Updating Natural Key"

2024-08-26 18:30 UTC, bradbanister commented on src/backend/EdFi.DataManagementService.Backend.Postgresql/Operation/UpdateDocumentById.cs
> +                        "Failure: Natural key does not match on update - {TraceId}",
Change to "identity" vs "natural key"

2024-08-26 18:34 UTC, bradbanister commented on src/backend/EdFi.DataManagementService.Backend.Postgresql.Test.Integration/UpdateTests.cs
> +
Need a test where something references the document before the identity change.

2024-08-26 18:37 UTC, bradbanister commented on src/backend/EdFi.DataManagementService.Backend.Postgresql/Operation/SqlAction.cs
> +                    @"UPDATE dms.Alias AS a
Does this work if a document references the document before the identity change? Doesn't the `Reference` table need updating? I don't see an update cascade setting on the FK in the 1000 SQL script, maybe that's all you need?

2024-08-27 02:19 UTC, bradbanister approved these changes

2024-08-27 02:32 UTC, bradbanister approved these changes

2024-08-27 02:32 UTC, merged