[DMS-341] List vendor applications
Ed-Fi-Alliance-OSS/Data-Management-Service pull request #311
Opened 2024-10-18 22:57 UTC by JBrenesSimpat

2024-10-21 16:37 UTC, JBrenesSimpat commented on src/config/datamodel/EdFi.DmsConfigurationService.DataModel/Application.cs
> +    public required IList<long> EducationOrganizationIds { get; set; } = [];
Rename this list to be equivalent to AdminAPI

2024-10-22 17:53 UTC, simpat-adam requested changes

2024-10-22 17:53 UTC, simpat-adam commented on src/config/backend/EdFi.DmsConfigurationService.Backend.Postgresql/VendorRepository.cs
> +                    {
need to set the vendor's Id in here `vendor.Id = vendorId;`

2024-10-22 17:53 UTC, simpat-adam commented on src/config/backend/EdFi.DmsConfigurationService.Backend.Postgresql/VendorRepository.cs
> +                        if (existingApplication == null && application != null)
`application` cannot be null here. You can remove the check. Also remove the `?` on line 213

2024-10-22 18:17 UTC, simpat-adam approved these changes

2024-10-22 18:17 UTC, merged